"""Behavioral examples for the opt-in attribution prototype."""

import subprocess

import check_ai_attribution as checker
import pytest
from shared.suite import initialize_git_repository, run_git


@pytest.fixture
def repo(tmp_path):
    write(tmp_path, "existing.txt", "old content\n")
    initialize_git_repository(tmp_path, "existing.txt")
    return tmp_path


def write(repo, name, text):
    path = repo / name
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8", newline="") as handle:
        handle.write(text)
    return path


def stage(repo, name, text):
    path = write(repo, name, text)
    run_git(repo, "add", "--", name)
    return path


def commit(repo, message="Update example"):
    run_git(repo, "commit", "-m", message)
    return run_git(repo, "rev-parse", "HEAD").stdout.strip()


@pytest.mark.parametrize(
    ("text", "rule"),
    [
        ("# Author: Claude Code", "ai-header"),
        ("// AUTHOR is OpenAI Codex", "ai-header"),
        ("\ufeff\t# author: claude-code\r", "ai-header"),
        ("<!-- Author: GitHub Copilot -->", "ai-header"),
        ("/* Author: ChatGPT */", "ai-header"),
        ("**Author:** `Claude_Code`", "ai-header"),
        ("**Generated by Claude Code**", "ai-footer"),
        ("**Co-authored-by:** Codex <bot@example.invalid>", "ai-trailer"),
        (
            "Co-authored-by: Claude Opus 5 (1M context) <noreply@anthropic.com>",
            "ai-trailer",
        ),
        ("Co-Authored-By: Claude Sonnet 4.5 <bot@example.invalid>", "ai-trailer"),
        ("Co authored by: Codex <bot@example.invalid>", "ai-trailer"),
        (
            "🤖 Generated with [Claude Code](https://claude.com/claude-code)",
            "ai-footer",
        ),
        ("; Generated by Claude Haiku 4.", "ai-footer"),
        ("Generated by Codex", "ai-footer"),
    ],
)
def test_explicit_attribution(text, rule):
    assert checker.classify(text) == rule


@pytest.mark.parametrize(
    "text",
    [
        "Co-authored-by: Human Contributor <human@example.invalid>",
        "Co-authored-by: Claude Shannon <human@example.invalid>",
        "Author: Claude",
        "Author: Codex Custodian",
        "Author: CodexTools",
        "Author: Claude Codebase",
        "Author: MyCodex",
        "Generated by tools/generate_validation_report.py",
        "Generated by Claude Code examples generator",
        "AI assisted the draft; I reviewed and tested it.",
        "Reviewed with Codex.",
        "Do not add Generated with Claude Code footers.",
        'tool = "Codex"',
        "# Copyright Claude Code Contributors; licensed under MIT",
        "# Source: Claude Code documentation",
        "# is_ai = yes",
        "# Author: Claude Code and Human Contributor",
    ],
)
def test_humans_disclosures_tools_and_provenance_are_not_findings(text):
    assert checker.classify(text) is None


def test_message_file_warns_without_mutation(tmp_path, capsys):
    path = write(
        tmp_path,
        "message",
        "\ufeffFix example\r\n\r\nCo-authored-by: Codex <bot@example.invalid>\r\nCo-authored-by: Human <human@example.invalid>\r\n",
    )
    before = path.read_bytes()
    assert checker.main(["--commit-msg", str(path)]) == 0
    output = capsys.readouterr().out
    assert ":3: ai-trailer:" in output
    assert "1 finding(s)" in output
    assert "human@example" not in output
    assert path.read_bytes() == before


@pytest.mark.parametrize(
    "data",
    [b"\xff", b"\0", b"x" * (checker.MAX_BYTES + 1)],
    ids=["invalid-utf8", "nul", "oversized"],
)
def test_bad_message_is_not_a_clean_result(tmp_path, capsys, data):
    path = tmp_path / "message"
    path.write_bytes(data)
    assert checker.main(["--commit-msg", str(path)]) == 2
    captured = capsys.readouterr()
    assert "incomplete" in captured.err
    assert "Report only" not in captured.out


def test_missing_message_and_repository(tmp_path, capsys):
    assert checker.main(["--commit-msg", str(tmp_path / "missing")]) == 2
    assert checker.main(["--staged", "--repo", str(tmp_path)]) == 2
    assert "ERROR" in capsys.readouterr().err


def test_partial_staging_reads_index_not_worktree(repo):
    path = stage(repo, "new file é.txt", "\ufeff# Author: Codex\r\n")
    path.write_bytes(b"# Author: Human\n")
    results, skipped = checker.scan(repo)
    assert results == [("new file é.txt", 1, "ai-header")]
    assert skipped == []
    stage(repo, "new file é.txt", "# Author: Human\n")
    path.write_bytes(b"# Author: Codex\n")
    assert checker.scan(repo)[0] == []


def test_only_added_lines_and_rename_changes_are_reported(repo):
    text = "# Author: Claude Code\n" + "unchanged line\n" * 20
    stage(repo, "before.txt", text)
    commit(repo)
    run_git(repo, "mv", "before.txt", "after.txt")
    assert checker.scan(repo)[0] == []
    stage(repo, "after.txt", text + "# Author: Codex\n")
    assert checker.scan(repo)[0] == [("after.txt", 22, "ai-header")]
    run_git(repo, "rm", "-f", "after.txt")
    assert checker.scan(repo)[0] == []


def test_diff_ignores_external_diff_and_textconv(repo):
    stage(repo, "existing.txt", "# Author: Codex\n")
    run_git(repo, "config", "diff.external", "must-not-be-executed")
    stage(repo, ".gitattributes", "*.txt diff=untrusted\n")
    run_git(repo, "config", "diff.untrusted.textconv", "must-not-be-executed")
    assert checker.scan(repo)[0] == [("existing.txt", 1, "ai-header")]


def test_exception_is_exact_and_has_reason(repo):
    stage(repo, "CLAUDE.md", "Author: Claude Code\n")
    stage(repo, "unrelated/CLAUDE.md", "Author: Claude Code\n")
    stage(repo, "resources/external.txt", "Author: Codex\n")
    stage(repo, "localisation/french/example_l_french.yml", "Author: Codex\n")
    stage(repo, "localisation/english/example_l_english.yml", "# Author: Codex\n")
    results, skipped = checker.scan(repo)
    assert {(path, line) for path, line, _ in results} == {
        ("unrelated/CLAUDE.md", 1),
        ("localisation/english/example_l_english.yml", 1),
    }
    assert len(skipped) == 3
    assert all(reason for _, reason in skipped)


def test_binary_and_nontext_are_explicitly_skipped(repo):
    path = stage(repo, "binary.txt", "placeholder")
    path.write_bytes(b"\0# Author: Codex")
    run_git(repo, "add", "binary.txt")
    stage(repo, "image.dds", "# Author: Codex")
    results, skipped = checker.scan(repo)
    assert results == []
    assert len(skipped) == 2
    assert any("binary" in reason for _, reason in skipped)


def test_symlink_is_never_followed(repo):
    blob = run_git(repo, "hash-object", "-w", "existing.txt").stdout.strip()
    run_git(repo, "update-index", "--add", "--cacheinfo", f"120000,{blob},link.txt")
    results, skipped = checker.scan(repo)
    assert results == []
    assert skipped == [("link.txt", "non-regular file (symlink or submodule)")]


@pytest.mark.parametrize(
    "data", [b"\xff", b"x" * (checker.MAX_BYTES + 1)], ids=["invalid-utf8", "oversized"]
)
def test_invalid_text_blob_fails(repo, data):
    path = repo / "bad.txt"
    path.write_bytes(data)
    run_git(repo, "add", "bad.txt")
    with pytest.raises(checker.ScanError):
        checker.scan(repo)


def test_branch_scans_new_messages_and_diff_but_not_base_history(repo):
    stage(repo, "legacy.txt", "# Author: Claude Code\n")
    base = commit(repo, "Legacy\n\nCo-authored-by: Codex <bot@example.invalid>")
    stage(repo, "new.txt", "safe\n# Author: Codex\n")
    head = commit(
        repo,
        "New\n\nGenerated with Claude Code\nCo-authored-by: Human <human@example.invalid>",
    )
    results, skipped = checker.scan(repo, base, head)
    assert results == [
        (f"commit {head[:12]}", 3, "ai-footer"),
        ("new.txt", 2, "ai-header"),
    ]
    assert skipped == []
    assert checker.scan(repo, head, head) == ([], [])


def test_metadata_only_commit_still_checked(repo):
    base = run_git(repo, "rev-parse", "HEAD").stdout.strip()
    run_git(repo, "commit", "--allow-empty", "-m", "Generated by Codex")
    results, _ = checker.scan(repo, base)
    assert len(results) == 1
    assert results[0][2] == "ai-footer"


def test_missing_refs_and_unrelated_history_fail(repo):
    with pytest.raises(checker.ScanError):
        checker.scan(repo, "does-not-exist")
    with pytest.raises(checker.ScanError):
        checker.scan(repo, "HEAD", "--help")
    base = run_git(repo, "rev-parse", "HEAD").stdout.strip()
    run_git(repo, "checkout", "--orphan", "unrelated")
    commit(repo)
    with pytest.raises(checker.ScanError):
        checker.scan(repo, base)


def test_shallow_clone_fails_visibly(repo, tmp_path_factory, capsys):
    clone = tmp_path_factory.mktemp("clone") / "repo"
    run_git(repo, "clone", "--depth=1", repo.as_uri(), str(clone))
    assert checker.main(["--repo", str(clone), "--base", "HEAD"]) == 2
    assert "complete history" in capsys.readouterr().err


def test_initial_commit_and_clean_index(tmp_path):
    run_git(tmp_path, "init")
    assert checker.scan(tmp_path) == ([], [])
    stage(tmp_path, "initial.txt", "Author is Codex\n")
    assert checker.scan(tmp_path)[0] == [("initial.txt", 1, "ai-header")]


def test_conflicted_index_is_incomplete(repo):
    base = run_git(repo, "rev-parse", "HEAD").stdout.strip()
    stage(repo, "existing.txt", "left\n")
    left = commit(repo)
    run_git(repo, "checkout", "-b", "right", base)
    stage(repo, "existing.txt", "right\n")
    commit(repo)
    with pytest.raises(subprocess.CalledProcessError):
        run_git(repo, "merge", left)
    with pytest.raises(checker.ScanError, match="unmerged"):
        checker.scan(repo)


@pytest.mark.parametrize("config", [{"x.md": ""}, {"x.md": None}, []])
def test_invalid_exemption_config_fails(monkeypatch, config):
    monkeypatch.setattr(checker, "validation_config", lambda *_: config)
    with pytest.raises(checker.ScanError):
        checker.exemptions()


def test_safe_diagnostics_and_git_errors(repo, capsys, monkeypatch):
    stage(repo, "example.txt", "Generated with Claude Code\n")
    assert checker.main(["--staged", "--repo", str(repo)]) == 0
    assert 'WARNING "example.txt":1: ai-footer:' in capsys.readouterr().out

    def timeout(*_args, **_kwargs):
        raise subprocess.TimeoutExpired("git", 30)

    monkeypatch.setattr(checker.subprocess, "run", timeout)
    assert checker.main(["--staged", "--repo", str(repo)]) == 2
    assert "incomplete" in capsys.readouterr().err


def test_head_requires_base():
    with pytest.raises(SystemExit, match="2"):
        checker.main(["--staged", "--head", "other"])


def test_git_interhunk_setting_does_not_flag_context(repo):
    stage(repo, "existing.txt", "one\nold\n# Author: Claude Code\nold\nfive\n")
    commit(repo)
    stage(repo, "existing.txt", "one\nnew\n# Author: Claude Code\nnew\nfive\n")
    run_git(repo, "config", "diff.interHunkContext", "3")
    assert checker.scan(repo)[0] == []


def test_diverged_base_excludes_base_only_history(repo):
    ancestor = run_git(repo, "rev-parse", "HEAD").stdout.strip()
    stage(repo, "base-only.txt", "Author: Codex\n")
    base = commit(repo, "Generated by Codex")
    run_git(repo, "checkout", "-b", "feature", ancestor)
    stage(repo, "feature.txt", "Author: Claude Code\n")
    head = commit(repo)
    assert checker.scan(repo, base, head)[0] == [("feature.txt", 1, "ai-header")]


def test_cli_entrypoint_and_skip_diagnostics(repo):
    stage(repo, "image.dds", "binary fixture")
    result = subprocess.run(
        [checker.sys.executable, checker.__file__, "--staged", "--repo", str(repo)],
        capture_output=True,
        text=True,
        check=True,
        timeout=30,
    )
    assert 'SKIP "image.dds": outside the prototype text suffix set' in result.stdout
    assert "0 finding(s); 1 skipped path(s)" in result.stdout
