title: "Millennium Dawn: A Modern Day Mod"
description: "Documentation for the Millennium Dawn: A Modern Day mod for the game Hearts of Iron IV."
baseurl: "/Millennium-Dawn"
url: "https://millenniumdawnmod.github.io"
lang: en
title_separator: " - "
logo: /uploads/main-menu.png

twitter:
  username: MillenniumDawn
  card: summary_large_image

markdown: kramdown
highlighter: rouge

sass:
  sass_dir: _sass
  style: compressed

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

navigation:
  - title: "Home"
    url: "/"
  - title: "FAQ"
    url: "/faq"
  - title: "Support"
    url: "/technical-support"
  - title: "Tutorials"
    url: "/tutorials"
  - title: "Resources"
    url: "/team-resources"
  - title: "Changelogs"
    url: "/changelogs"
  - title: "Dev Diaries"
    url: "/dev-diaries-list"
  - title: "Country List"
    url: "/countries-list"
  - title: "Code Style Guide"
    url: "/dev-resources/code-stylization-guide"

social:
  - name: "GitHub"
    url: "https://github.com/MillenniumDawn/Millennium-Dawn"
  - name: "Steam Workshop"
    url: "https://steamcommunity.com/sharedfiles/filedetails/?id=2777392649"
  - name: "Reddit"
    url: "https://www.reddit.com/r/MillenniumDawn/"
  - name: "Discord"
    url: "https://discord.gg/millenniumdawn"
  - name: "Twitter"
    url: "https://twitter.com/MillenniumDawn"
