l_simp_chinese:
 AUTOMATION_SETTINGS_OPEN_TT: "打开自动化设置"
 AUTOMATION_SETTINGS_TITLE: "自动化设置"
 AUTOMATION_SETTINGS_DESC: "在一个面板中管理重复性操作和通知偏好设置。其他位置的现有控件仍然可用。"
 AUTOMATION_SETTINGS_GENERAL_PAGE: "通用"
 AUTOMATION_SETTINGS_SPACE_PAGE: "卫星"
 AUTOMATION_SETTINGS_INFLUENCE_PAGE: "影响力"
 AUTOMATION_SETTINGS_SPACE_DESC: "配置卫星自动生产、发射和卫星升级。"
 AUTOMATION_SETTINGS_INFLUENCE_DESC: "配置定期执行的操作，以保护我国政府免受外国影响。"
 AUTOMATION_SETTINGS_SPACE_SAVE_BUTTON_TT: "将太空计划中暂存的有效载荷清单存储为§Y自定义§!计划，并切换到该计划。\n\n§Y先决条件：§!\n[!automation_space_save_button_click_enabled]"
 AUTOMATION_SETTINGS_SPACE_UPGRADE_BUTTON_TT: "在现有轨道覆盖范围允许的情况下，将每个星座推广到最新一代的研究对象。\n\n§Y先决条件：§!\n[!automation_space_upgrade_button_click_enabled]"
 AUTOMATION_SETTINGS_NOTIFICATIONS_HEADER: "通知和偏好设置"
 AUTOMATION_SETTINGS_UN_HEADER: "联合国"
 AUTOMATION_SETTINGS_DIPLOMACY_HEADER: "外交"
 AUTOMATION_SETTINGS_NATO_HEADER: "北约"
 AUTOMATION_SETTINGS_ENERGY_HEADER: "能源"
 AUTOMATION_SETTINGS_PP_RESERVE: "政治点数储备"
 AUTOMATION_SETTINGS_PP_RESERVE_VALUE: "£pol_power [?automation_pp_reserve|0]"
 AUTOMATION_SETTINGS_PP_RESERVE_TT: "消耗政治点数的自动行动会等到政治点数足以支付其成本且不低于储备值时才会执行。手动行动不受影响。\n\n£click_left §Y左键点击§!：调整§Y1§!\n£key_ctrl + £click_left §YCtri+左键点击§!：调整§Y10§!\n£key_shift + £click_left §YShift+左键点击§!：调整§Y100§!"
 AUTOMATION_SETTINGS_PP_RESERVE_PLUS_TT: "£click_left §Y左键点击§!：增加§Y1§!\n£key_ctrl + £click_left §YCtrl+左键点击§!：增加§Y10§!\n£key_shift + £click_left §YShift+左键点击§!：增加§Y100§!"
 AUTOMATION_SETTINGS_PP_RESERVE_MINUS_TT: "£click_left §Y左键点击§!：减少§Y1§!\n£key_ctrl + £click_left §YCtrl+左键点击§!：减少§Y10§!\n£key_shift + £click_left §YShift+左键点击§!：减少§Y100§!"
 AUTOMATION_SETTINGS_CORRUPTION: "自动拒绝腐败提议"
 AUTOMATION_SETTINGS_CORRUPTION_TT: "自动跳过腐败提议。启用此功能后，相关活动及其加成将不会显示。"
 AUTOMATION_SETTINGS_FOREIGN_ELECTION: "外国选举通知"
 AUTOMATION_SETTINGS_FOREIGN_ELECTION_TT: "显示其他国家选举的新闻通知。"
 AUTOMATION_SETTINGS_RAID_NOTIFICATIONS: "影响突袭通知"
 AUTOMATION_SETTINGS_RAID_NOTIFICATIONS_TT: "显示其他国家之间的影响力突袭事件。即使禁用此功能，针对我们的突袭事件仍会被报告。"
 AUTOMATION_SETTINGS_INFLUENCE_REPORT: "月度自动影响力报告"
 AUTOMATION_SETTINGS_INFLUENCE_REPORT_TT: "显示受自动影响国家/地区的月度报告。"
 AUTOMATION_SETTINGS_INVESTMENT_ACCEPTANCE: "自动接受投资提议"
 AUTOMATION_SETTINGS_INVESTMENT_ACCEPTANCE_TT: "自动接受所有收到的国际投资提议。启用此功能将禁用自动拒绝功能。"
 AUTOMATION_SETTINGS_INVESTMENT_REJECTION: "自动拒绝投资提议"
 AUTOMATION_SETTINGS_INVESTMENT_REJECTION_TT: "自动拒绝所有国际投资提议。启用此功能将禁用自动接受提议。"
 AUTOMATION_SETTINGS_REINVESTMENT: "国际投资再投资"
 AUTOMATION_SETTINGS_REINVESTMENT_TT: "选择国际投资的每周收益如何在国库和再投资之间分配。"
 AUTOMATION_SETTINGS_REINVEST_OFF: "禁用"
 AUTOMATION_SETTINGS_REINVEST_OFF_TT: "将所有国际投资收益上缴国库。"
 AUTOMATION_SETTINGS_REINVEST_FULL: "全部"
 AUTOMATION_SETTINGS_REINVEST_FULL_TT: "将所有国际投资收益进行再投资。"
 AUTOMATION_SETTINGS_REINVEST_SPLIT: "拆分"
 AUTOMATION_SETTINGS_REINVEST_SPLIT_TT: "将国际投资收益的一半上缴国库，另一半进行再投资。"
 AUTOMATION_SETTINGS_FUEL_PURCHASE: "自动购买燃料"
 AUTOMATION_SETTINGS_FUEL_PURCHASE_TT: "立即购买燃料，然后每28天检查一次，当燃料储备低于20%时再次购买。禁用此功能可取消未来的购买。"
 AUTOMATION_SETTINGS_INTERNAL_INVESTMENTS: "重复选定的内部投资"
 AUTOMATION_SETTINGS_INTERNAL_INVESTMENTS_TT: "启用此功能后，每日需支付§R0.15§!£pol_power 政治点数。在状态视图中右键点击内部投资按钮，选择要重复进行的投资状态和类型。选定的投资项目每周检查一次，并在有空位、国库能够支付当前成本且政治点数储备得以维持的情况下运行。"
 AUTOMATION_SETTINGS_ANTARCTICA_RESUPPLY: "自动补给南极站点"
 AUTOMATION_SETTINGS_ANTARCTICA_RESUPPLY_TT: "从11月到3月，在剩余燃料使用时间不足15天时自动为我们的南极科考站订购燃料；从4月到10月，在剩余燃料使用时间不足30天时自动为我们的南极科考站订购燃料。运输费用§R$0.25b/1000单位燃料§!，极地冬季费用翻倍。订单要等到国库能够支付全部费用后才能执行。"
 AUTOMATION_SETTINGS_ENERGY_CONSUMPTION_POLICY: "自动消费政策"
 AUTOMATION_SETTINGS_SC_VOTE: "安理会默认投票"
 AUTOMATION_SETTINGS_SC_VOTE_TT: "选择我们如何对安全理事会决议进行自动投票。再次单击所选选项即可返回手动投票模式。"
 AUTOMATION_SETTINGS_GA_VOTE: "大会默认投票"
 AUTOMATION_SETTINGS_GA_VOTE_TT: "选择我们如何对大会决议进行自动投票。再次单击所选选项即可返回手动投票模式。"
 AUTOMATION_SETTINGS_VOTE_YES: "是"
 AUTOMATION_SETTINGS_VOTE_NO: "否"
 AUTOMATION_SETTINGS_VOTE_ABSTAIN: "弃权"
 AUTOMATION_SETTINGS_SC_ACCEPT_TT: "对安理会所有决议自动投赞成票。"
 AUTOMATION_SETTINGS_SC_REJECT_TT: "对安理会所有决议，均自动投否决票。常任理事国将在适用情况下行使否决权。"
 AUTOMATION_SETTINGS_SC_ABSTAIN_TT: "自动对安理会所有决议投弃权票。"
 AUTOMATION_SETTINGS_GA_ACCEPT_TT: "对大会的每一项决议自动投赞成票。"
 AUTOMATION_SETTINGS_GA_REJECT_TT: "对大会的每一项决议自动投否决票。"
 AUTOMATION_SETTINGS_GA_ABSTAIN_TT: "自动对大会所有决议投弃权票。"
 AUTOMATION_SETTINGS_SATELLITE_REJECTION: "阻止AI卫星接入提议"
 AUTOMATION_SETTINGS_SATELLITE_REJECTION_TT: "阻止AI国家提供对其军用和民用卫星系统的共享访问权限。人类玩家仍然可以发送此类请求。"
 AUTOMATION_SETTINGS_NATO_RATIFICATION: "自动批准北约成员国身份"
 AUTOMATION_SETTINGS_NATO_RATIFICATION_TT: "自动花费§Y20§!点£pol_power 政治点数储备来批准每个北约候选国的入盟申请。批准程序将等到政治点数储备能够维持在一定水平后才会进行。"
 AUTOMATION_SETTINGS_INFLUENCE_HEADER: "影响力防御"
 AUTOMATION_SETTINGS_COMBAT_FOREIGN_INFLUENCE: "自动对抗外国影响"
 AUTOMATION_SETTINGS_COMBAT_FOREIGN_INFLUENCE_TT: "启用此功能后，每日需支付§R0.05§!点£pol_power 政治点数。如有可用点数，则自动消耗§Y100§!点£pol_power 政治点数，使国内独立度提升§G2.5%§!。每100天重复一次。当政府受到游说或任何一项支出会导致政治点数低于储备时，自动功能暂停。"
 AUTOMATION_SETTINGS_ATTACK_FOREIGN_INFLUENCERS: "自动攻击外国影响者"
 AUTOMATION_SETTINGS_ATTACK_FOREIGN_INFLUENCERS_TT: "启用此功能后，每日需支付§R0.05§!点£pol_power 政治点数。系统将自动花费§Y125§!点£pol_power 政治点数，发起一场为期60天的针对最强合格外国影响力人物的行动。每次只能进行一场行动。不符合资格、已被游说或处于冷却期的目标将被跳过。当任何一项支出导致政治点数低于储备时，自动化流程将暂停。"
 AUTOMATION_SETTINGS_INFLUENCE_COST_NOTE: "每个启用选项每天花费§R0.05§!£pol_power 。两个选项一起启用每天花费§R0.10§!£pol_power 。"
 AUTOMATION_SETTINGS_ECONOMY_PAGE: "经济"
 AUTOMATION_SETTINGS_ECONOMY_DESC: "选择要自动管理的税收、公共支出、投资和能源采购。将鼠标悬停在标题或选项上可查看详细信息。"
 AUTOMATION_SETTINGS_TAX_HEADER: "税率"
 AUTOMATION_SETTINGS_BUDGET_HEADER: "预算法"
 AUTOMATION_SETTINGS_TAX_SUMMARY: "税收政策每周最多调整一个百分点，以应对预算平衡、债务和稳定性问题。\n\n手动更改不会影响自动化功能。"
 AUTOMATION_SETTINGS_BUDGET_SUMMARY: "已启用的预算会向预期支出方向调整一级。每周最多只有一项预算会发生变化，优先级轮换。增加预算需要预算盈余。手动修改法律法规后，自动化功能仍保持启用状态。"
 AUTOMATION_SETTINGS_POPULATION_TAX: "人口税：[?population_tax_rate|0]%"
 AUTOMATION_SETTINGS_CORPORATE_TAX: "企业税：[?corporate_tax_rate|0]%"
 AUTOMATION_SETTINGS_POPULATION_TAX_TT: "根据预算平衡、债务和稳定度，每周自动调整人口税一个百分点。此调整遵循税收变更限制，并支付超出储备金的正常政治力量成本。手动调整税收时，此选项保持启用状态。"
 AUTOMATION_SETTINGS_CORPORATE_TAX_TT: "根据预算余额和债务情况，每周自动调整企业所得税一个百分点。此操作遵循税收变更限制，并支付超出储备金的正常政治权力成本。手动调整税收时，此选项仍保持启用状态。"
 AUTOMATION_SETTINGS_BUDGET_BUREAUCRACY: "行政：[?bureau_law|0] / [?expected_adm_spending|0]"
 AUTOMATION_SETTINGS_BUDGET_BUREAUCRACY_TT: "自动将行政支出逐步提升至预期水平。数字显示当前水平和预期水平。正常法律限制和政治权力消耗适用。增加支出需要盈余，并在即将破产时暂停。政治权力储备得以保留。手动修改法律将保持此选项启用状态。"
 AUTOMATION_SETTINGS_BUDGET_CRIME_FIGHTING: "警务：[?police_law|0] / [?expected_police_spending|0]"
 AUTOMATION_SETTINGS_BUDGET_CRIME_FIGHTING_TT: "自动将警务支出逐步提升至预期水平。数字显示当前水平和预期水平。正常的法律限制和政治权力消耗仍然适用。增加警务支出需要盈余，并且在即将破产时暂停。政治权力储备将予以保留。手动修改法律将保持此选项启用状态。"
 AUTOMATION_SETTINGS_BUDGET_EDUCATION_BUDGET: "教育：[?education_law|0] / [?expected_edu_spending|0]"
 AUTOMATION_SETTINGS_BUDGET_EDUCATION_BUDGET_TT: "自动将教育支出逐步提升至预期水平。数字显示当前水平和预期水平。正常法律限制和政治权力消耗适用。增加教育支出需要盈余，并在即将破产时暂停。政治权力储备将予以保留。手动修改法律将保持此选项启用状态。"
 AUTOMATION_SETTINGS_BUDGET_HEALTH_BUDGET: "医疗保健：[?health_law|0] / [?expected_health_spending|0]"
 AUTOMATION_SETTINGS_BUDGET_HEALTH_BUDGET_TT: "自动将医疗保健支出逐步提升至预期水平。数字显示了当前水平和预期水平。正常法律限制和政治权力成本适用。增加支出需要盈余，并且在即将破产时暂停。政治权力储备将予以保留。手动修改法律将保持此选项启用状态。"
 AUTOMATION_SETTINGS_BUDGET_SOCIAL_BUDGET: "福利：[?social_law|0] / [?expected_welfare_spending|0]"
 AUTOMATION_SETTINGS_BUDGET_SOCIAL_BUDGET_TT: "自动将福利支出逐步提升至预期水平。数字显示当前水平和预期水平。正常法律限制和政治权力消耗适用。增加福利支出需要盈余，并在即将破产时暂停。政治权力储备得以保留。手动修改法律将保持此选项启用状态。"
 AUTOMATION_SETTINGS_BUDGET_MILITARY_SPENDING: "军事开支：[?military_law|0] / [?expected_military_sp|0]"
 AUTOMATION_SETTINGS_BUDGET_MILITARY_SPENDING_TT: "自动将军费开支逐步提升至预期水平。数字显示当前水平和预期水平。正常法律限制和政治权力消耗适用。增加军费开支需要财政盈余，并在即将破产时暂停。政治权力储备将予以保留。手动修改法律将保持此选项启用状态。"
 AUTOMATION_SETTINGS_GENERAL_PAGE_TT: "配置通用自动化，例如联合国行动、通知偏好设置和其他次要自动化操作。"
 AUTOMATION_SETTINGS_SPACE_PAGE_TT: "配置卫星自动生产、发射和卫星升级。\n\n§Y先决条件：§!\n[!automation_settings_space_page_button_click_enabled]"
 AUTOMATION_SETTINGS_INFLUENCE_PAGE_TT: "配置影响力自动化，例如影响力防御和攻击。"
 AUTOMATION_SETTINGS_ECONOMY_PAGE_TT: "配置经济自动化功能，例如税率、预算法律、投资和能源。"
 AUTOMATION_SETTINGS_NUCLEAR_ENRICHMENT: "阻止AI核燃料请求"
 AUTOMATION_SETTINGS_NUCLEAR_ENRICHMENT_TT: "禁止AI控制的国家向其他国家发送§Y核燃料§!购买请求。人类玩家仍然可以发送请求。"
 AUTOMATION_SETTINGS_INVESTMENT_HEADER: "投资"